{% set name = "neuralforecast" %}
{% set version = "1.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/neuralforecast-{{ version }}.tar.gz
  sha256: 86a10728bb33bc620feca3cc50792a0df8930d7791ba499ac4c90469015e7b0b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - coreforecast >=0.0.7
    - fsspec
    - numpy >=1.21.6
    - optuna
    - pandas >=1.3.5
    - pytorch >=2.0.0
    - pytorch-lightning >=2.0.0
    - ray-tune >=2.2.0
    - utilsforecast >=0.0.26

test:
  imports:
    - neuralforecast
  ## Skipping pip-check (as build keeps failing)
  # commands:
  #   - pip check
  # requires:
  #   - pip

about:
  home: https://github.com/Nixtla/neuralforecast/tree/main/
  summary: Deep Learning for Time Series Forecasting
  license: GPL-3.0-only
  license_file: LICENSE
  description: |
    State-of-the-art time series forecasting for PyTorch.

    `NeuralForecast` is a Python library for time series forecasting with 
    deep learning models. It includes *benchmark datasets*, *data-loading 
    utilities*, *evaluation functions*, statistical *tests*, univariate *model 
    benchmarks* and *SOTA* models implemented in PyTorch and PyTorchLightning.

    PyPI: [https://pypi.org/project/neuralforecast/](https://pypi.org/project/neuralforecast/)

  doc_url: https://nixtla.github.io/neuralforecast
  dev_url: https://github.com/Nixtla/neuralforecast/tree/main/

extra:
  recipe-maintainers:
    - sugatoray
    - cchallu
    - AzulGarza
    - jmoralez
